"""
PayShield Pipeline

Wires:

    evidence detectors
        ↓
    entity graph
        ↓
    correlator
        ↓
    orchestrator
        ↓
    explainability

Supports:
- correlated mode
- independent mode
- live entity-graph enrichment
- explicit rejection of unknown pipeline step types
- CIC-IDS2017 dataset evidence
- PaySim dataset evidence

IMPORTANT:

Dataset-specific handling exists only at the evidence-ingestion boundary.

CIC-IDS2017 uses the existing CIC detector.

PaySim transactions use the existing transaction/entity-graph path.

Neither dataset has its own decision engine.
"""

from __future__ import annotations

from .entity_graph.entity_graph import EntityGraph
from .evidence.lure.detector import classify as classify_lure
from .evidence.network.detector import (
    classify as classify_network,
    classify_cic_flow,
)
from .evidence.session.detector import classify as classify_session
from .models.case import Case
from .correlator import Correlator
from .orchestrator import Orchestrator


orchestrator = Orchestrator()


# =====================================================================
# DATASET PROVENANCE
# =====================================================================

def _attach_network_provenance(
    case: Case,
    step: dict,
) -> None:
    """
    Attach dataset provenance to the network evidence that was just
    generated by the existing correlator.

    The correlator remains responsible for the actual detection and
    attack-state transition.

    This helper only enriches the resulting evidence with provenance
    metadata from the source record.
    """

    if not case.evidence:
        return

    evidence = case.evidence[-1]

    if evidence.get("stream") != "network":
        return

    if step.get("source") != "CIC-IDS2017":
        return

    evidence["source"] = "CIC-IDS2017"

    if step.get("dataset_record_id"):
        evidence["dataset_record_id"] = (
            step["dataset_record_id"]
        )

    if step.get("ground_truth_label") is not None:
        evidence["ground_truth_label"] = (
            step["ground_truth_label"]
        )

    # Preserve useful source-level context for investigation and
    # validation without feeding it back into detection.
    for field in (
        "destination_port",
        "flow_duration",
        "total_packets",
        "total_bytes",
        "flow_packets_per_second",
        "flow_bytes_per_second",
        "packet_asymmetry",
        "connection_flags",
    ):
        if field in step:
            evidence[field] = step[field]


def _attach_transaction_provenance(
    case: Case,
    step: dict,
    evidence_start_index: int,
) -> None:
    """
    Attach PaySim provenance to transaction/entity-graph evidence
    generated by the existing correlator.

    If the transaction is ordinary and therefore does not create
    correlator evidence, there is nothing to enrich.
    """

    if step.get("source") != "PaySim":
        return

    if len(case.evidence) <= evidence_start_index:
        return

    for evidence in case.evidence[
        evidence_start_index:
    ]:
        if evidence.get("stream") != "entity_graph":
            continue

        evidence["source"] = "PaySim"

        if step.get("dataset_record_id"):
            evidence["dataset_record_id"] = (
                step["dataset_record_id"]
            )

        if step.get("transaction_type") is not None:
            evidence["transaction_type"] = (
                step["transaction_type"]
            )

        if step.get("dataset_step") is not None:
            evidence["dataset_step"] = (
                step["dataset_step"]
            )

        if step.get("ground_truth_fraud") is not None:
            evidence["ground_truth_fraud"] = (
                step["ground_truth_fraud"]
            )

        if step.get("ground_truth_flagged_fraud") is not None:
            evidence["ground_truth_flagged_fraud"] = (
                step["ground_truth_flagged_fraud"]
            )


# =====================================================================
# MAIN PIPELINE
# =====================================================================

def run_case(
    case_id: str,
    script: list[dict],
    graph: EntityGraph,
    correlated: bool = True,
) -> dict:
    """
    Run one PayShield case.

    All evidence streams ultimately enter the same Correlator,
    Attack State machine, Investigation representation, Timeline,
    Orchestrator and Explainability layers.
    """

    case = Case(case_id=case_id)

    correlator = Correlator(
        case,
        graph=graph,
    )

    independent_results = []

    for step in script:

        t = step.get("t")
        step_type = step["type"]

        # ==========================================================
        # LURE
        # ==========================================================

        if step_type == "lure":

            result = classify_lure(
                step["text"],
                case_id=case_id,
            )

            identifier = step.get(
                "identifier"
            )

            account_id = step.get(
                "account_id"
            )

            identifier_kind = step.get(
                "identifier_kind"
            )

            # Register the observed account <-> identifier relationship
            # in the existing EntityGraph.
            if (
                account_id
                and identifier
                and identifier_kind
                in {"phone", "vpa"}
            ):
                graph.add_shared_identifier_link(
                    account_id,
                    str(identifier),
                    identifier_kind,
                )

            if correlated:

                correlator.feed_lure(
                    result,
                    identifier=identifier,
                    t=t,
                )

            else:

                graph_hit = (
                    bool(identifier)
                    and graph.identifier_in_confirmed_scam(
                        identifier
                    )
                )

                probability = (
                    min(
                        0.99,
                        result.probability + 0.25,
                    )
                    if graph_hit
                    else result.probability
                )

                case.log(
                    "suspicious_message_detected",
                    stream="lure",
                    t=t,
                    probability=probability,
                    matched_pattern=result.matched_pattern,
                    identifier_flagged_by_graph=graph_hit,
                )

                mini_action = (
                    "WARN"
                    if probability >= 0.8
                    else (
                        "MONITOR"
                        if probability >= 0.5
                        else "NONE"
                    )
                )

                independent_results.append(
                    {
                        "stream": "lure",
                        "action": mini_action,
                        "detail": result.matched_pattern,
                    }
                )

        # ==========================================================
        # NETWORK
        # ==========================================================

        elif step_type == "network":

            # ------------------------------------------------------
            # REAL CIC-IDS2017
            # ------------------------------------------------------
            #
            # The existing CIC detector consumes the complete
            # normalized CIC record.
            #
            # Ground-truth labels remain metadata only.
            # ------------------------------------------------------

            if step.get("source") == "CIC-IDS2017":

                result = classify_cic_flow(
                    step,
                    case_id=case_id,
                )

            # ------------------------------------------------------
            # EXISTING GENERIC NETWORK PATH
            # ------------------------------------------------------

            else:

                result = classify_network(
                    step["failed_logins"],
                    step["requests_per_minute"],
                    step["distinct_source_ips"],
                    case_id=case_id,
                )

            if correlated:

                evidence_count_before = len(
                    case.evidence
                )

                correlator.feed_network(
                    result,
                    t=t,
                )

                # CIC provenance is added only after the existing
                # correlator has generated the evidence.
                if (
                    step.get("source")
                    == "CIC-IDS2017"
                    and len(case.evidence)
                    > evidence_count_before
                ):
                    _attach_network_provenance(
                        case,
                        step,
                    )

            else:

                case.log(
                    "network_anomaly_detected",
                    stream="network",
                    t=t,
                    probability=result.probability,
                    matched_pattern=result.matched_pattern,
                )

                mini_action = (
                    "STEP_UP_AUTH"
                    if result.probability >= 0.5
                    else "MONITOR"
                )

                independent_results.append(
                    {
                        "stream": "network",
                        "action": mini_action,
                        "detail": result.matched_pattern,
                    }
                )

        # ==========================================================
        # SESSION
        # ==========================================================

        elif step_type == "session":

            result = classify_session(
                step["is_new_device"],
                step["geo_velocity_kmph"],
                step["login_hour_local"],
                step["remote_access_tool_detected"],
                case_id=case_id,
            )

            device_id = step.get(
                "device_id"
            )

            account_id = step.get(
                "account_id"
            )

            # Register the observed account <-> device relationship
            # in the existing EntityGraph.
            if account_id and device_id:

                graph.add_shared_device_link(
                    account_id,
                    str(device_id),
                )

            if correlated:

                correlator.feed_session(
                    result,
                    device_id=device_id,
                    t=t,
                )

            else:

                linked = (
                    graph.device_linked_to_flagged_account(
                        device_id
                    )
                    if device_id
                    else []
                )

                anomaly_score = (
                    min(
                        0.99,
                        result.probability + 0.2,
                    )
                    if linked
                    else result.probability
                )

                case.log(
                    "session_anomaly_detected",
                    stream="session",
                    t=t,
                    anomaly_score=anomaly_score,
                    triggering_feature=result.matched_pattern,
                    device_linked_to_flagged_accounts=linked,
                )

                mini_action = (
                    "MONITOR"
                    if anomaly_score >= 0.5
                    else "NONE"
                )

                independent_results.append(
                    {
                        "stream": "session",
                        "action": mini_action,
                        "detail": result.matched_pattern,
                    }
                )

        # ==========================================================
        # TRANSACTION
        # ==========================================================

        elif step_type == "transaction":

            if correlated:

                evidence_count_before = len(
                    case.evidence
                )

                # The existing Correlator owns:
                #
                # transaction
                #     ↓
                # EntityGraph
                #     ↓
                # PageRank
                # Betweenness
                # Louvain
                # mule signals
                #     ↓
                # Attack State
                #
                # No PaySim-specific decision is made here.

                correlator.feed_transaction(
                    step["amount"],
                    step["from_account"],
                    step["to_account"],
                    timestamp=t,
                )

                if (
                    step.get("source")
                    == "PaySim"
                ):
                    _attach_transaction_provenance(
                        case,
                        step,
                        evidence_count_before,
                    )

            else:

                graph.add_transaction_edge(
                    step["from_account"],
                    step["to_account"],
                    step["amount"],
                    t,
                )

                signal = graph.compute_mule_signal(
                    step["to_account"]
                )

                mule_hit = (
                    signal["is_confirmed_mule"]
                    or bool(
                        signal[
                            "confirmed_mules_in_community"
                        ]
                    )
                    or signal["is_structural_hub"]
                )

                case.log(
                    "large_transaction_initiated",
                    stream="entity_graph",
                    t=t,
                    amount=step["amount"],
                    to_account=step["to_account"],
                    **signal,
                )

                mini_action = (
                    "MONITOR"
                    if mule_hit
                    else "NONE"
                )

                independent_results.append(
                    {
                        "stream": "entity_graph",
                        "action": mini_action,
                        "detail": (
                            "mule-ring signal"
                            if mule_hit
                            else "no flag"
                        ),
                    }
                )

                case.add_evidence(
                    "entity_graph",
                    amount=step["amount"],
                    to_account=step["to_account"],
                    **signal,
                )

                if step.get("source") == "PaySim":
                    _attach_transaction_provenance(
                        case,
                        step,
                        len(case.evidence) - 1,
                    )

        # ==========================================================
        # UNKNOWN STEP TYPE
        # ==========================================================

        else:

            raise KeyError(
                f"Unknown pipeline step type: {step_type}"
            )

    # ==============================================================
    # FINAL DECISION
    # ==============================================================

    if correlated:

        # The Orchestrator remains the sole policy-decision component.
        final_action = orchestrator.decide(
            case
        )

        from .explainability import (
            generate_explanation,
        )

        explanation = generate_explanation(
            case,
            graph,
        )

        return {
            "mode": "correlated",
            "case": case.to_dict(),
            "final_action": final_action,
            "explanation": explanation,
        }

    else:

        return {
            "mode": "independent",
            "case": case.to_dict(),
            "independent_results": independent_results,
            "final_action": (
                "NO ACTION TAKEN "
                "(no cross-stream correlation)"
            ),
            "explanation": [
                f"{r['stream']}: "
                f"{r['action']} "
                f"({r['detail']})"
                for r in independent_results
            ],
        }