from .case import InvestigationCase
from .correlation import extract_correlations


def build_investigation_case(result: dict, graph) -> InvestigationCase:
    """
    Build the evaluator-facing investigation representation from the
    exact PayShield pipeline result and EntityGraph used for the case.

    The investigation is a projection of backend state. It does not
    recalculate detection, correlation, attack state, graph structure,
    or policy decisions.
    """

    case = result["case"]

    # ---------------------------------------------------------------
    # Entity graph
    #
    # EntityGraph.to_viz_dict() is the single source of truth for
    # graph visualization data. Preserve both nodes and edges rather
    # than dropping the relationships after graph construction.
    # ---------------------------------------------------------------

    graph_data = graph.to_viz_dict()

    # ---------------------------------------------------------------
    # Timeline / correlation
    # ---------------------------------------------------------------

    timeline = case.get("timeline", [])

    correlations = extract_correlations(
        timeline
    )

    # ---------------------------------------------------------------
    # Investigation representation
    # ---------------------------------------------------------------

    return InvestigationCase(
        case_id=case["case_id"],
        status="Under Investigation",
        evidence=case.get("evidence", []),

        # Existing field retained for compatibility.
        entities=graph_data.get("nodes", []),

        # Actual graph relationships generated by EntityGraph.
        edges=graph_data.get("edges", []),

        timeline=timeline,

        correlations=correlations,

        attack_state=case.get("attack_state"),

        risk_index=case.get("risk_index"),

        policy_decision=case.get("final_action"),

        findings=result.get("explanation", []),
    )